@API_KEY=

# @name Get location by name
GET https://api.openweathermap.org/geo/1.0/direct?q=bangkok&limit=1&appid={{API_KEY}}

###

# @name Get current weather
# @prompt lat
# @prompt lon
GET https://api.openweathermap.org/data/2.5/weather?lat={{lat}}&lon={{lon}}&appid={{API_KEY}}

###

# @name Get 5-day / 3-hour forecast
# @prompt lat
# @prompt lon
GET https://api.openweathermap.org/data/2.5/forecast?lat={{lat}}&lon={{lon}}&appid={{API_KEY}}
